### ISSUE TITLE
Question: what AWS IAM policies are required?

### ISSUE THREAD

**Issue by sectsect** [awslabs/lightsail-auto-snapshots#10]
Thanks for useful package.

I'm trying to figure out what permissions are required.
But it does not work well.

Can you show me required `IAM` policies?

**Comment by jpignata** [comment]
See https://github.com/awslabs/lightsail-auto-snapshots/blob/master/lightsail-auto-snapshots.yaml#L40

**Comment by sectsect** [comment]
As far as I have tried, I guess that not only the policy for `lightsail` but also the following IAM policy is necessary.
I'd like to narrow down the IAM policies further.

```js
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:*",
                "events:*",
                "lambda:*",
                "s3:*",
                "lightsail:*",
                "cloudformation:*"
            ],
            "Resource": "*"
        }
    ]
}
```
