### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Karl456** [awslabs/lightsail-auto-snapshots#3]
This isn't an issue, more of a question.

I've attempted to get this to work using AWS Lambda, but I'm unable to do so.

Are you able to provide instructions on how to use this with AWS Lambda?

**Comment by jpignata** [comment]
The provided Serverless Application Model (SAM) template does everything you need to get this working on Lambda. If you choose to do it manually, you should be able to copy and paste the code into a function and schedule it to run via a CloudWatch Events trigger. Hope that helps!

**Comment by Karl456** [comment]
Unfortunately this hasn't really helped. I've gone on to CloudFormation and uploaded the .yaml template file from the repo, however when going through the setup I get the following error:

Error creating change set: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [AutoSnapshot] is invalid. 'CodeUri' is not a valid S3 Uri of the form "s3://bucket/key" with optional versionId query parameter.

Which relates to the line in the template file which specifies ./lambda, what am I missing?

**Comment by jpignata** [comment]
Ahh, sorry I missed this. You must use the provided deploy script to
package the contents of the Lambda function. Can you give the directions in
the README a shot?
