### ISSUE TITLE
Include instructions for changing snapshot frequency

### ISSUE THREAD

**Issue by zevross-spatial** [awslabs/lightsail-auto-snapshots#6]
The usage instructions indicate that the only options for the script are snapshot retention time and region. But it's easy enough after the script has run to go into cloud watch and adjust the event rule that's created so that the snapshots could be run weekly, monthly, etc-

**Comment by jpignata** [comment]
Sure, that's definitely an option! For simplicity, using the stack is probably best as it keeps the stack state in sync. Thanks for the suggestion.
