### ISSUE TITLE
do not work

### ISSUE THREAD

**Issue by markkap** [awslabs/lightsail-auto-snapshots#7]
(yes I hate this kind of bug reports/questions myself, sorry)

cloned the repo, ran deploy and got 
> usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument subcommand: Invalid choice, valid choices are:

> list

aws --version gets
> aws-cli/1.2.9 Python/3.4.3 Linux/3.13.0-119-generic

**Comment by blasto333** [comment]
You need to upgrade aws-cli to latest version 

Works on aws-cli/1.11.155 Python/2.7.6 Linux/3.13.0-119-generic botocore/1.7.13

**Comment by jpignata** [comment]
Thanks @blasto333! @markkap if you still need help please let me know.
